index_file_train: /home/yy785/datasets/lyft_release_test/ImageSets/fw70_2m_train_idx.txt
p2score_path: /home/yy785/datasets/lyft_release_test/training/gt_segmentation
scan_path: /home/yy785/datasets/lyft_release_test/training/velodyne/
calib_path: /home/yy785/datasets/lyft_release_test/training/calib/

image_shape: [1024, 1224]